### ISSUE TITLE
idearia/php-logger/src/logger.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by spyesx** [Idearia/php-logger#3]
Hi,

I just deployed my application to find that the class was not found despite a classic `autoload` from composer.

```php
<?php
require_once __DIR__.'/../vendor/autoload.php';

use \Idearia\Logger;

\Idearia\Logger::info( 'message']);
```

I still get this error:

```text
PHP Fatal error:  Uncaught Error: Class 'Idearia\Logger' not found in /builds/PATH/TO/PHP/script.php:34
```

Then I tried to `dump-autoload` and composer skips the class because "it does not comply with psr-4 autoloading standard".

```console
$ php composer dump-autoload --optimize
> Generating optimized autoload files
> Class Idearia\Logger located in ./vendor/idearia/php-logger/src/logger.php does not comply with psr-4 autoloading standard. Skipping.
```
Versions are:

- Docker base: debian:stable

```console
$ php composer -V
> Composer version 2.0.9 2021-01-27 16:09:27

$ php -v
> PHP 7.4.15 (cli) (built: Feb 12 2021 14:48:10) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies
```

**Comment by coccoinomane** [comment]
Thank you for submitting the issue, it completely got under my radar 😅
@milkamil93 submitted a pull request that should have fixed the issue > https://github.com/Idearia/php-logger/pull/4
Please let me know if this is not the case.
Cheers,
Guido
