### ISSUE TITLE
Access to undeclared static property log_level 

### ISSUE THREAD

**Issue by Fr34k9** [Idearia/php-logger#6]
Looks great! Only thing I found:
Log_level is not declared and can't be used.

**Comment by coccoinomane** [comment]
Hi @Fr34k9  and thank you for your report!

I couldn't reproduce the error, can you please provide a snippet?

Could it be that you tried to access `self::log_level` instead of `self::$log_level`?

**Comment by Fr34k9** [comment]
Somehow I just found out I used an older version. But when using now 
`composer require idearia/php-logger`
there are a lot of other packages loaded as well. Is this intended?

`Package operations: 35 installs, 0 updates, 0 removals
  - Installing sebastian/version (3.0.2): Loading from cache
  - Installing sebastian/resource-operations (3.0.3): Loading from cache
  - Installing sebastian/recursion-context (4.0.4): Loading from cache
  - Installing sebastian/object-reflector (2.0.4): Loading from cache
  - Installing sebastian/object-enumerator (4.0.4): Loading from cache
  - Installing sebastian/global-state (5.0.5): Loading from cache
  - Installing sebastian/exporter (4.0.4): Loading from cache
  - Installing sebastian/environment (5.1.4): Loading from cache
  - Installing sebastian/diff (4.0.4): Loading from cache
  - Installing sebastian/comparator (4.0.6): Loading from cache
  - Installing sebastian/code-unit (1.0.8): Loading from cache
  - Installing sebastian/cli-parser (1.0.1): Loading from cache
  - Installing phpunit/php-timer (5.0.3): Loading from cache
  - Installing phpunit/php-text-template (2.0.4): Loading from cache
  - Installing phpunit/php-invoker (3.1.1): Loading from cache
  - Installing phpunit/php-file-iterator (3.0.6): Loading from cache
  - Installing theseer/tokenizer (1.2.1): Loading from cache
  - Installing nikic/php-parser (v4.13.2): Loading from cache
  - Installing sebastian/lines-of-code (1.0.3): Loading from cache
  - Installing sebastian/complexity (2.0.2): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Loading from cache
  - Installing phpunit/php-code-coverage (9.2.15): Loading from cache
  - Installing doctrine/instantiator (1.4.1): Loading from cache
  - Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.25.0): Loading from cache
  - Installing webmozart/assert (1.10.0): Loading from cache
  - Installing phpdocumentor/type-resolver (1.6.1): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.3.0): Loading from cache
  - Installing phpspec/prophecy (v1.15.0): Loading from cache
  - Installing phar-io/version (3.2.1): Loading from cache
  - Installing phar-io/manifest (2.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.11.0): Loading from cache
  - Installing sebastian/type (3.0.0): Loading from cache
  - Installing phpunit/phpunit (9.5.20): Loading from cache
  - Installing idearia/php-logger (1.2): Loading from cache
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-pcov (*)
phpunit/php-code-coverage suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing ext-xdebug (*)`

**Comment by coccoinomane** [comment]
My bad: I added `phpunit` as a normal dependency 🤦🏻‍♂️

I fixed it in the latest version, could you please try again?

**Comment by Fr34k9** [comment]
Works like a charm, thx for effort

**Comment by coccoinomane** [comment]
@Fr34k9 
Thanks mate :-)
