### ISSUE TITLE
Late Static Bindings problem

### ISSUE THREAD

**Issue by GlaceDream** [Idearia/php-logger#7]
This logger is really helpful! I just have one problem with the overriding of static properties.

## PROBLEM
To customize the Logger, I wanted to use the first approach described in README: "extend the class and override the static properties". I created the following "CustomLogger" class, and set the properties in order to write in a file called "main.log". But, I found that nothing is written in the log file because the methods use static properties of Logger with "self::" instead of "::static" ([late static binding](https://www.php.net/manual/en/language.oop5.late-static-bindings.php)).

```php
<?php
use Idearia\Logger;

class CustomLogger extends Logger {
    // Show debug messages, info messages, warnings and errors
    public static $log_level = 'debug';

    // Unable writing to file
    public static $write_log = true;

    // Customize the log file path
    public static $log_dir = __DIR__;
    public static $log_file_name = 'main';

    // To prevent printing to STDOUT
    public static $print_log = false;
}
```

## ALTERNATIVE SOLUTION
I found an alternative solution that consists in changing static properties in the class constructor. This solution implies to use an instance of CustomLogger.

```php
<?php
use Idearia\Logger;

class CustomLogger extends Logger {

    public function __construct()
    {
        // Show debug messages, info messages, warnings and errors
        self::$log_level = 'debug';

        // Unable writing to file
        self::$write_log = true;

        // Customize the log file path
        self::$log_dir = __DIR__;
        self::$log_file_name = 'main';

        // To prevent printing to STDOUT
        self::$print_log = false;
    }
}
```

## QUESTIONS
So, my questions are:
- Was it designed to be like this?
- Do you plan to use Late Static Bindings?

**Comment by coccoinomane** [comment]
Thanks @JeremieLevain , that was indeed a bug! I fixed it in https://github.com/Idearia/php-logger/pull/8 and merged to master. Could you please check whether it now works as intended for you? 🙂

**Comment by GlaceDream** [comment]
It is working perfectly fine! Thanks for the correction.
