### ISSUE TITLE
Tring to get things going

### ISSUE THREAD

**Issue by QuesnelJ** [Idearia/php-logger#9]
Does any one know what I'm doing wrong?

```
use Idearia\Logger;
			
require_once getRunningServer () . '/_fromExternal/php-logger/src/Logger.php';
$Logger = new Idearia\Logger;
			
Logger::$log_level = 'debug';
Logger::debug( "variable x is false" );
Logger::info( "program started" );
Logger::warning( "variable not set, something bad might happen" );
Logger::error( "file not found, exiting" );
```

**Comment by coccoinomane** [comment]
Hi @QuesnelJ,
You do not need the third line (`$Logger = ...`).
The class only provides static methods for you to use.
No need to instantiate it.

**Comment by QuesnelJ** [comment]
Thanks for your assistance.

This helped a bit as we've moved down a line or two. I'm now getting the error:

```
Fatal error: Uncaught Error: Undefined constant "Idearia\STDOUT" in /vol...
```

at the debug line. ```Logger::debug( "variable x is false" );```

Any idea @coccoinomane?

**Comment by QuesnelJ** [comment]
Ok, apparently ```Logger::$print_log = false;``` fixes the problem. But I can't seem to be able to send the output to the browser.

Suggestions?

**Comment by coccoinomane** [comment]
Hi @QuesnelJ, sorry for the late reply.
`php-logger` is a server-side tool written in PHP.  To log information to the browser, you need to use Javascript, which is a browser-side language.
Cheers,
Cocco
